DISTRO_FEATURES:append = " libc-abi-breaker-xdp"

KERNEL_FEATURES:append = " features/tsn/tsn.scc"
KERNEL_FEATURES:append = " features/bpf/bpf.scc"
KERNEL_FEATURES:append = " features/net/xdp/xdp.scc"
KERNEL_FEATURES:append = " cfg/debug/sched/debug-schedstats.scc"

COMPATIBLE_MACHINE:pn-libbpf-iotg = "intel-x86-64"
COMPATIBLE_MACHINE:pn-iotg-tsn-ref-sw = "intel-x86-64"
