COMPATIBLE_MACHINE:pn-qat17 ??= "intel-x86-64"
COMPATIBLE_MACHINE:pn-qat20 ??= "intel-x86-64"
COMPATIBLE_MACHINE:pn-qatlib ??= "intel-x86-64"
COMPATIBLE_MACHINE:pn-qatzip ??= "intel-x86-64"

# Use PREFERRED_PROVIDER_virtual/qat and PREFERRED_PROVIDER_virtual/lib32-qat
# to choose the QAT package provider. It can be qat17 or qatlib for now. Please
# note that they cannot be used at the same time.
#
# Comment the following two lines and uncomment the corresponding two lines about
# PREFERRED_PROVIDER_virtual/qat and PREFERRED_PROVIDER_virtual/lib32-qat, if
# you want to use qat20 or qatlib instead of qat17.
#
# Note: qat17 and qat20 don't support multilib, due to inheriting the module-base class.
PREFERRED_PROVIDER_virtual/qat ??= "qat17"
PREFERRED_PROVIDER_virtual/lib32-qat ??= "qat17"

#PREFERRED_PROVIDER_virtual/qat ??= "qat20"
#PREFERRED_PROVIDER_virtual/lib32-qat ??= "qat20"

#PREFERRED_PROVIDER_virtual/qat ??= "qatlib"
#PREFERRED_PROVIDER_virtual/lib32-qat ??= "qatlib"

# Unlike qat17 and qat20 who inherit module, have to
# explicitly add qatlib to NON_MULTILIB_RECIPES.
NON_MULTILIB_RECIPES:append = " qatlib"

MACHINE_EXTRA_RRECOMMENDS += "linux-firmware-qat"
